adminUser:
  password: vault:dconde-cjxd-3/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: dconde@cloudbees.com
  token: vault:dconde-cjxd-3/pipelineUser:token
  username: daveconde
prow:
  hmacToken: vault:dconde-cjxd-3/prow:hmacToken
